name: doctors_appointments
description: Doctors Appointments

publish_to: 'none'

version: 2.4.0+27

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  google_maps_flutter: ^2.6.0
  google_maps_place_picker_mb:
    git:
      url: https://github.com/SmarterVision/google_maps_place_picker_mb.git
      ref: master  # or latest stable version
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  firebase_messaging: ^14.8.1
  cloud_firestore: ^4.16.1
  firebase_storage: ^11.7.1
  firebase_crashlytics: 3.5.7    
  firebase_remote_config: ^4.3.18    
  get: 4.6.6
  get_storage: 2.1.1
  dio: 4.0.6
  dio_http_cache: 0.3.0
  google_fonts: 6.2.1
  cached_network_image: 3.3.1
  carousel_slider: 5.0.0
  flutter_svg: 2.0.10+1
  flutter_staggered_grid_view: 0.7.0
  image_picker: 1.1.1
  cupertino_icons: 1.0.8
  shimmer: 3.0.0
  intl_phone_field: 3.2.0
  date_picker_timeline: 1.2.6
  webview_flutter: 4.7.0
  flutter_html: 3.0.0-beta.2
  url_launcher: 6.2.6
  jitsi_meet_flutter_sdk: 10.2.1
  map_launcher: 3.3.0
  google_api_headers: ^2.0.3
 

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.3
  win32: 5.5.4
  flutter_native_splash: 2.2.16
  flutter_lints: 3.0.2

dependency_overrides:
  json_annotation: 4.8.0

flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/img/
    - assets/icon/
